(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("level_1",
{ "height":10,
 "infinite":false,
 "layers":[
        {
         "data":[1610612743, 3758096392, 3758096392, 3758096392, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2147483656, 11, 11, 2684354568, 2684354567, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2147483656, 11, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2147483657, 10, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1610612743, 1610612744, 7, 2147483656, 11, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3221225480, 11, 8, 2147483656, 11, 8, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3221225480, 11, 8, 3221225479, 2684354568, 2684354567, 1, 1, 1, 1, 1, 1, 2147483652, 2, 4, 1, 1, 1, 1, 1, 1, 1, 2147483657, 10, 9, 1, 1, 1, 1, 1, 1, 1, 1, 2147483652, 2, 2, 2, 4, 1, 1, 1, 1, 1, 1, 3221225480, 11, 8, 1, 1, 1, 1, 1, 1, 1, 2147483652, 2, 2, 2, 2, 2, 4, 1, 1, 1610612743, 1610612744, 1610612744, 11, 11, 8, 1, 1, 1, 1, 1, 1, 2147483654, 5, 5, 5, 5, 5, 5, 5, 6, 1, 3221225479, 2684354568, 2684354568, 2684354568, 2684354568, 2684354567],
         "height":10,
         "id":4,
         "name":"ground",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":22,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 22, 22, 22, 22, 22, 22, 0, 22, 22, 22, 22, 0, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 22, 22, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 22, 22, 0, 22, 22, 22, 0, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 22, 22, 0, 22, 22, 0, 0, 0, 22, 22, 22, 0, 0, 0, 0, 0, 0, 0, 22, 22, 22, 22, 22, 22, 0, 22, 0, 0, 0, 0, 0, 22, 22, 0, 0, 0, 0, 0, 0, 0, 22, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 22, 22, 0, 0, 0, 0, 0, 0, 22, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0],
         "height":10,
         "id":5,
         "name":"reference",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":22,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":6,
         "name":"mountain",
         "objects":[
                {
                 "height":0,
                 "id":4,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-515.151515151515,
                         "y":557.575757575758
                        }, 
                        {
                         "x":524.242424242424,
                         "y":566.666666666667
                        }],
                 "rotation":0,
                 "type":"Mountain",
                 "visible":true,
                 "width":0,
                 "x":1257.57575757576,
                 "y":618.181818181818
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":7,
         "name":"red_tower",
         "objects":[
                {
                 "height":120,
                 "id":5,
                 "name":"",
                 "rotation":0,
                 "type":"Red_tower",
                 "visible":true,
                 "width":120,
                 "x":360.606060606061,
                 "y":242.424242424242
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":9,
         "name":"red_house",
         "objects":[
                {
                 "height":237,
                 "id":6,
                 "name":"",
                 "rotation":0,
                 "type":"Red_house",
                 "visible":true,
                 "width":236,
                 "x":362,
                 "y":362
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":10,
         "name":"refection_tower",
         "objects":[
                {
                 "height":114.666666666667,
                 "id":7,
                 "name":"",
                 "rotation":0,
                 "type":"refection_tower",
                 "visible":true,
                 "width":116,
                 "x":481.333333333333,
                 "y":242.666666666667
                }, 
                {
                 "height":121.333333333333,
                 "id":8,
                 "name":"",
                 "rotation":0,
                 "type":"refection_tower",
                 "visible":true,
                 "width":118.666666666667,
                 "x":722.666666666667,
                 "y":360
                }, 
                {
                 "height":118,
                 "id":9,
                 "name":"",
                 "rotation":0,
                 "type":"refection_tower",
                 "visible":true,
                 "width":120,
                 "x":1320,
                 "y":242
                }, 
                {
                 "height":116,
                 "id":10,
                 "name":"",
                 "rotation":0,
                 "type":"refection_tower",
                 "visible":true,
                 "width":116,
                 "x":1322,
                 "y":4
                }, 
                {
                 "height":122,
                 "id":11,
                 "name":"",
                 "rotation":0,
                 "type":"refection_tower",
                 "visible":true,
                 "width":122,
                 "x":2036,
                 "y":358
                }, 
                {
                 "height":122,
                 "id":12,
                 "name":"",
                 "rotation":0,
                 "type":"refection_tower",
                 "visible":true,
                 "width":120,
                 "x":2158,
                 "y":840
                }, 
                {
                 "height":118,
                 "id":13,
                 "name":"",
                 "rotation":0,
                 "type":"refection_tower",
                 "visible":true,
                 "width":126,
                 "x":1916,
                 "y":2
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":11,
         "name":"blue_tower",
         "objects":[
                {
                 "height":120,
                 "id":14,
                 "name":"",
                 "rotation":0,
                 "type":"blue_tower",
                 "visible":true,
                 "width":122,
                 "x":1316,
                 "y":116
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":12,
         "name":"blue_house",
         "objects":[
                {
                 "height":116,
                 "id":15,
                 "name":"",
                 "rotation":0,
                 "type":"Sky",
                 "visible":true,
                 "width":360,
                 "x":838,
                 "y":120
                }, 
                {
                 "height":122,
                 "id":16,
                 "name":"",
                 "rotation":0,
                 "type":"blue_house",
                 "visible":true,
                 "width":232,
                 "x":964,
                 "y":238
                }, 
                {
                 "height":116,
                 "id":17,
                 "name":"",
                 "rotation":0,
                 "type":"Sky",
                 "visible":true,
                 "width":238,
                 "x":1560,
                 "y":120
                }, 
                {
                 "height":122,
                 "id":18,
                 "name":"",
                 "rotation":0,
                 "type":"Sky",
                 "visible":true,
                 "width":118,
                 "x":1922,
                 "y":116
                }, 
                {
                 "height":120,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "type":"blue_house",
                 "visible":true,
                 "width":240,
                 "x":1558,
                 "y":238
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":13,
         "name":"yellow_tower",
         "objects":[
                {
                 "height":122,
                 "id":21,
                 "name":"",
                 "rotation":0,
                 "type":"yellow_tower",
                 "visible":true,
                 "width":118,
                 "x":2038,
                 "y":838
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":14,
         "name":"yellow houses",
         "objects":[
                {
                 "height":239.5,
                 "id":23,
                 "name":"",
                 "rotation":0,
                 "type":"yellow_house",
                 "visible":true,
                 "width":238.5,
                 "x":2039.5,
                 "y":600.5
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":15,
         "name":"trees",
         "objects":[
                {
                 "height":0,
                 "id":24,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0,
                         "y":240
                        }, 
                        {
                         "x":-360,
                         "y":240
                        }, 
                        {
                         "x":-360,
                         "y":600
                        }, 
                        {
                         "x":360,
                         "y":600
                        }, 
                        {
                         "x":360,
                         "y":0
                        }, 
                        {
                         "x":0,
                         "y":0
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":360,
                 "y":600
                }, 
                {
                 "height":0,
                 "id":25,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":2,
                         "y":122
                        }, 
                        {
                         "x":122,
                         "y":122
                        }, 
                        {
                         "x":122,
                         "y":2
                        }, 
                        {
                         "x":242,
                         "y":2
                        }, 
                        {
                         "x":242,
                         "y":-118
                        }, 
                        {
                         "x":722,
                         "y":-118
                        }, 
                        {
                         "x":722,
                         "y":-238
                        }, 
                        {
                         "x":2,
                         "y":-238
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":598,
                 "y":238
                }, 
                {
                 "height":0,
                 "id":26,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-2,
                         "y":474
                        }, 
                        {
                         "x":118,
                         "y":474
                        }, 
                        {
                         "x":118,
                         "y":354
                        }, 
                        {
                         "x":238,
                         "y":354
                        }, 
                        {
                         "x":238,
                         "y":234
                        }, 
                        {
                         "x":358,
                         "y":234
                        }, 
                        {
                         "x":358,
                         "y":114
                        }, 
                        {
                         "x":478,
                         "y":114
                        }, 
                        {
                         "x":478,
                         "y":234
                        }, 
                        {
                         "x":598,
                         "y":234
                        }, 
                        {
                         "x":598,
                         "y":354
                        }, 
                        {
                         "x":718,
                         "y":354
                        }, 
                        {
                         "x":718,
                         "y":474
                        }, 
                        {
                         "x":838,
                         "y":474
                        }, 
                        {
                         "x":838,
                         "y":594
                        }, 
                        {
                         "x":958,
                         "y":594
                        }, 
                        {
                         "x":958,
                         "y":714
                        }, 
                        {
                         "x":1078,
                         "y":714
                        }, 
                        {
                         "x":1078,
                         "y":474
                        }, 
                        {
                         "x":958,
                         "y":474
                        }, 
                        {
                         "x":958,
                         "y":-6
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":842,
                 "y":486
                }, 
                {
                 "height":0,
                 "id":28,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0,
                         "y":120
                        }, 
                        {
                         "x":360,
                         "y":120
                        }, 
                        {
                         "x":360,
                         "y":240
                        }, 
                        {
                         "x":480,
                         "y":240
                        }, 
                        {
                         "x":480,
                         "y":360
                        }, 
                        {
                         "x":600,
                         "y":360
                        }, 
                        {
                         "x":600,
                         "y":240
                        }, 
                        {
                         "x":480,
                         "y":240
                        }, 
                        {
                         "x":480,
                         "y":120
                        }, 
                        {
                         "x":480,
                         "y":0
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":1440,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":29,
                 "name":"",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0,
                         "y":360
                        }, 
                        {
                         "x":120,
                         "y":360
                        }, 
                        {
                         "x":120,
                         "y":480
                        }, 
                        {
                         "x":240,
                         "y":480
                        }, 
                        {
                         "x":240,
                         "y":360
                        }, 
                        {
                         "x":600,
                         "y":360
                        }, 
                        {
                         "x":600,
                         "y":0
                        }],
                 "rotation":0,
                 "type":"tree",
                 "visible":true,
                 "width":0,
                 "x":2040,
                 "y":0
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":16,
 "nextobjectid":30,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.2.0",
 "tileheight":120,
 "tilesets":[
        {
         "firstgid":1,
         "source":"maplayouts.tsx"
        }, 
        {
         "firstgid":12,
         "source":"4-way_cell_tower_pink.tsx"
        }, 
        {
         "firstgid":21,
         "source":"housefrontt.tsx"
        }, 
        {
         "firstgid":22,
         "source":"tree.tsx"
        }, 
        {
         "firstgid":23,
         "source":"houseright.tsx"
        }, 
        {
         "firstgid":24,
         "source":"colorful_building.tsx"
        }, 
        {
         "firstgid":25,
         "source":"Skyscraper.tsx"
        }],
 "tilewidth":120,
 "type":"map",
 "version":1.2,
 "width":22
});